<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>RachaqaKost — Operasional Kos</title>@include('partials.branding-head')<link rel="stylesheet" href="{{ asset('assets/rachaqakost.css') }}"><link rel="stylesheet" href="{{ asset('assets/rachaqakost-fixes.css') }}?v=20260907-logo"><link rel="stylesheet" href="{{ asset('assets/dashboard-extras.css') }}?v=20260907-logo"></head><body>
@php
$tabs=['dashboard'=>['⌂','Ringkasan'],'rooms'=>['▦','Kamar'],'tenants'=>['◎','Penghuni'],'form-drafts'=>['▤','Draft Formulir'],'form-builder'=>['⚙','Atur Formulir'],'payments'=>['↗','Pembayaran'],'expenses'=>['↘','Pengeluaran'],'maintenance'=>['◇','Maintenance'],'website'=>['◉','Homepage'],'users'=>['♙','Tim']];
$titles=['dashboard'=>'Ringkasan operasional','rooms'=>'Kamar & kategori','tenants'=>'Data penghuni','form-drafts'=>'Draft Formulir Penghuni','form-builder'=>'Pengaturan Formulir','payments'=>'Pembayaran sewa','expenses'=>'Pengeluaran kos','maintenance'=>'Maintenance kamar','website'=>'Homepage Pemasaran','users'=>'Akses tim'];
$ownerOnlyTabs=['form-builder','website','users'];
$occupied=$rooms->where('status','TERISI')->count();$empty=$rooms->where('status','KOSONG')->count();$maintenanceCount=$rooms->where('status','MAINTENANCE')->count();$occupancy=$rooms->count()?round($occupied/$rooms->count()*100):0;
@endphp
<div class="shell"><aside class="sidebar"><div class="brand"><span class="brandmark">K</span><div><b>RachaqaKost</b><small>Operational OS</small></div></div><nav class="nav">@foreach($tabs as $key=>$tab)@if(!in_array($key,$ownerOnlyTabs,true)||auth()->user()->isOwner())<a href="{{ route('dashboard',['tab'=>$key]) }}" class="{{ $activeTab===$key?'active':'' }}"><span class="ico">{{ $tab[0] }}</span>{{ $tab[1] }}</a>@endif @endforeach @if(auth()->user()->isOwner())<div class="nav-separator"></div><a href="{{ route('finance') }}"><span class="ico">Rp</span>Keuangan</a><a href="{{ route('imports.index') }}"><span class="ico">⇧</span>Import Data</a><a href="{{ route('home') }}" target="_blank"><span class="ico">↗</span>Lihat Website</a>@endif</nav><div class="profile"><b>{{ auth()->user()->name }}</b><small>{{ auth()->user()->role==='OWNER'?'Owner / Admin':'Penjaga Kos' }}</small><form method="post" action="{{ route('logout') }}">@csrf<button class="logout">Keluar dari workspace</button></form></div></aside>
<main class="main"><header class="top"><div><h1>{{ $titles[$activeTab] }}</h1><p>{{ now()->translatedFormat('l, d F Y') }} · Database lokal CyberPanel</p></div></header>
@if(session('success'))<div class="toast">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="toast error">{{ $errors->first() }}</div>@endif

@if($activeTab==='dashboard')
<section class="period-panel">
    <form class="period-filter" method="get" action="{{ route('dashboard') }}">
        <input type="hidden" name="tab" value="dashboard">
        <input type="hidden" name="cashflow_from" value="{{ $cashflowFrom->toDateString() }}">
        <input type="hidden" name="cashflow_to" value="{{ $cashflowTo->toDateString() }}">
        <div class="period-filter__intro"><span class="period-filter__icon">▣</span><div><b>Periode ringkasan</b><small>Atur rentang pendapatan, pengeluaran, dan margin.</small></div></div>
        <div class="period-filter__controls">
            <label class="period-filter__field"><span>Dari tanggal</span><input type="date" name="from" value="{{ $reportFrom->toDateString() }}" required></label>
            <span class="period-filter__arrow">→</span>
            <label class="period-filter__field"><span>Sampai tanggal</span><input type="date" name="to" value="{{ $reportTo->toDateString() }}" required></label>
            <button class="btn period-filter__apply">Terapkan</button>
            <a class="btn secondary period-filter__reset" href="{{ route('dashboard') }}">Reset</a>
        </div>
    </form>
</section>
<section class="kpis"><article class="kpi"><label>Pendapatan periode<i>↗</i></label><strong>Rp {{ number_format($income/1000000,1,',','.') }} jt</strong><small>{{ $incomeTransactionCount }} transaksi · {{ $reportFrom->translatedFormat('d M') }}–{{ $reportTo->translatedFormat('d M Y') }}</small></article><article class="kpi"><label>Pengeluaran periode<i style="background:var(--orangeSoft);color:#a85f25">↘</i></label><strong>Rp {{ number_format($expenseTotal/1000000,1,',','.') }} jt</strong><small>{{ $expenseTransactionCount }} transaksi · Margin Rp {{ number_format($profit/1000000,1,',','.') }} jt</small></article><article class="kpi"><label>Kamar kosong<i style="background:#e7eafa;color:var(--blue)">▦</i></label><strong>{{ $empty }} kamar</strong><small>Dari {{ $rooms->count() }} total kamar</small></article><article class="kpi"><label>Perlu perhatian<i style="background:var(--redSoft);color:var(--red)">!</i></label><strong>{{ $dueSoon->count()+$maintenanceCount }} item</strong><small>{{ $dueSoon->count() }} tempo · {{ $maintenanceCount }} maintenance</small></article></section>
<section class="grid2"><article class="panel cashflow-panel"><div class="panelhead cashflow-head"><div><h2>Arus kas realtime</h2><p>{{ $cashflowFrom->translatedFormat('d M Y') }}–{{ $cashflowTo->translatedFormat('d M Y') }} · Tampilan {{ strtolower($cashflowGranularity) }}</p></div><span class="badge">Maks. 1 tahun</span></div><form class="cashflow-filter" method="get" action="{{ route('dashboard') }}"><input type="hidden" name="tab" value="dashboard"><input type="hidden" name="from" value="{{ $reportFrom->toDateString() }}"><input type="hidden" name="to" value="{{ $reportTo->toDateString() }}"><label><span>Dari</span><input type="date" name="cashflow_from" value="{{ $cashflowFrom->toDateString() }}" required></label><span>→</span><label><span>Sampai</span><input type="date" name="cashflow_to" value="{{ $cashflowTo->toDateString() }}" required></label><button class="btn small">Tampilkan</button></form><div class="panelbody"><div class="cashflow-chart-wrap"><div class="chart cashflow-chart" style="--cashflow-points:{{ $cashflow->count() }}">@foreach($cashflow as $point)<div class="chartcol"><div class="bars"><button type="button" class="bar" data-cashflow-bar data-tooltip="Pendapatan {{ $point['label'] }} · Rp {{ number_format($point['income'],0,',','.') }}" aria-label="Pendapatan {{ $point['label'] }} Rp {{ number_format($point['income'],0,',','.') }}" style="height:{{ max(2,round($point['income']/$maxCashflow*100)) }}%"></button><button type="button" class="bar exp" data-cashflow-bar data-tooltip="Pengeluaran {{ $point['label'] }} · Rp {{ number_format($point['expense'],0,',','.') }}" aria-label="Pengeluaran {{ $point['label'] }} Rp {{ number_format($point['expense'],0,',','.') }}" style="height:{{ max(2,round($point['expense']/$maxCashflow*100)) }}%"></button></div><small>{{ $point['label'] }}</small></div>@endforeach</div></div><div class="cashflow-value" id="cashflowValue" hidden>Pilih salah satu bar.</div><div class="legend"><span><i class="dot"></i>Pendapatan</span><span><i class="dot orange"></i>Pengeluaran</span><span>Klik bar untuk nominal</span></div></div></article><article class="panel"><div class="panelhead"><div><h2>Okupansi kamar</h2><p>Kondisi unit sekarang</p></div></div><div class="panelbody"><div class="ringwrap"><div class="ring" style="--v:{{ $occupancy }}"><span><b>{{ $occupancy }}%</b>terisi</span></div></div><div class="mini"><div><b>{{ $occupied }}</b><small>Terisi</small></div><div><b>{{ $empty }}</b><small>Kosong</small></div><div><b>{{ $maintenanceCount }}</b><small>Perbaikan</small></div></div></div></article></section>
<section class="grid2"><article class="panel"><div class="panelhead"><div><h2>Jatuh tempo terdekat</h2><p>7 hari ke depan dan yang terlambat</p></div></div><div class="panelbody due">@forelse($dueSoon->take(6) as $t)@php($waUrl=$t->whatsappUrl($whatsappTemplate))<div class="dueitem"><span class="roompill">{{ $t->room->number }}</span><div><b>{{ $t->name }}</b><small>{{ $t->billingCycleLabel() }} · Rp {{ number_format($t->billingRate(),0,',','.') }}</small></div><span class="badge {{ $t->isOverdue()?'red':'orange' }}">{{ $t->dueStatusLabel() }}</span>@if($waUrl)<a class="wa-button compact" href="{{ $waUrl }}" target="_blank" rel="noopener noreferrer" aria-label="Follow-up {{ $t->name }} melalui WhatsApp">WhatsApp</a>@endif</div>@empty<div class="empty">Tidak ada tagihan mendesak.</div>@endforelse</div></article><article class="panel"><div class="panelhead"><div><h2>Maintenance terbaru</h2><p>Riwayat biaya per kamar</p></div></div><div class="panelbody due">@forelse($maintenances->take(6) as $m)<div class="dueitem"><span class="roompill">{{ $m->room->number }}</span><div><b>{{ $m->title }}</b><small>{{ $m->reported_at->format('d M Y') }} · Rp {{ number_format($m->cost,0,',','.') }}</small></div></div>@empty<div class="empty">Belum ada riwayat maintenance.</div>@endforelse</div></article></section>
@endif

@if($activeTab==='rooms')
<section class="sectionhead"><div><h2>Kategori & harga</h2><p>Satu kategori dapat melayani sewa harian, mingguan, dan bulanan.</p></div>@if(auth()->user()->isOwner())<button class="btn" data-open="categoryModal">+ Kategori</button>@endif</section>
<div class="cards3">@forelse($categories as $c)
<article class="catcard" style="--accent:{{ $c->color }}"><b>{{ $c->name }}</b><div class="category-prices"><span><small>Harian</small><strong>Rp {{ number_format($c->daily_price,0,',','.') }}</strong></span><span><small>Mingguan</small><strong>Rp {{ number_format($c->weekly_price,0,',','.') }}</strong></span><span><small>Bulanan</small><strong>Rp {{ number_format($c->monthly_price,0,',','.') }}</strong></span></div><small>{{ $c->rooms_count }} kamar tersedia di kategori ini</small>
@if(auth()->user()->isOwner())<details class="edit"><summary>Atur kategori</summary><form class="editform" method="post" action="{{ route('categories.update',$c) }}">@csrf @method('PATCH')<input name="name" value="{{ $c->name }}" required><label class="compact-label">Harga harian</label><div class="currency-input"><span>Rp</span><input type="text" name="daily_price" data-currency inputmode="numeric" value="{{ number_format((float)$c->daily_price,0,',','.') }}" required></div><label class="compact-label">Harga mingguan</label><div class="currency-input"><span>Rp</span><input type="text" name="weekly_price" data-currency inputmode="numeric" value="{{ number_format((float)$c->weekly_price,0,',','.') }}" required></div><label class="compact-label">Harga bulanan</label><div class="currency-input"><span>Rp</span><input type="text" name="monthly_price" data-currency inputmode="numeric" value="{{ number_format((float)$c->monthly_price,0,',','.') }}" required></div><input type="color" name="color" value="{{ $c->color }}"><button class="btn small">Simpan</button></form>@if($c->rooms_count===0)<form class="delete-resource-form" method="post" action="{{ route('categories.destroy',$c) }}" onsubmit="return confirm('Hapus kategori ini? Tindakan ini tidak dapat dibatalkan.')">@csrf @method('DELETE')<button class="btn danger small">Hapus kategori</button></form>@else<div class="delete-resource-form"><button class="btn danger small" type="button" disabled>Hapus kategori</button><small>Pindahkan atau hapus {{ $c->rooms_count }} kamar terlebih dahulu.</small></div>@endif</details>@endif
</article>@empty<div class="empty">Belum ada kategori.</div>@endforelse</div>
<section class="sectionhead"><div><h2>Semua kamar</h2><p>Kelola kategori, lantai, dan status kamar.</p></div><button class="btn" data-open="roomModal">+ Tambah kamar</button></section>
<div class="roomgrid">@forelse($rooms as $r)
<article class="roomcard" style="--accent:{{ $r->category->color }}"><div class="row"><h3>#{{ $r->number }}</h3><span class="badge {{ $r->status==='MAINTENANCE'?'orange':($r->status==='KOSONG'?'gray':'') }}">{{ str($r->status)->headline() }}</span></div><small>{{ $r->category->name }} · Lantai {{ $r->floor }}</small><p>{{ $r->activeTenant?->name ?? ($r->status==='MAINTENANCE'?'Sedang diperbaiki':'Siap ditempati') }}</p><details class="edit"><summary>Edit kamar</summary><form class="editform" method="post" action="{{ route('rooms.update',$r) }}">@csrf @method('PATCH')<input name="number" value="{{ $r->number }}" required><input type="number" name="floor" value="{{ $r->floor }}" min="1" required><select name="room_category_id">@foreach($categories as $c)<option value="{{ $c->id }}" @selected($r->room_category_id===$c->id)>{{ $c->name }}</option>@endforeach</select><select name="status">@foreach(['KOSONG','TERISI','MAINTENANCE'] as $s)<option @selected($r->status===$s)>{{ $s }}</option>@endforeach</select><button class="btn small">Simpan kamar</button></form>@if(auth()->user()->isOwner())@if($r->tenants_count===0&&$r->maintenances_count===0&&$r->import_rows_count===0)<form class="delete-resource-form" method="post" action="{{ route('rooms.destroy',$r) }}" onsubmit="return confirm('Hapus kamar ini? Tindakan ini tidak dapat dibatalkan.')">@csrf @method('DELETE')<button class="btn danger small">Hapus kamar</button></form>@else<div class="delete-resource-form"><button class="btn danger small" type="button" disabled>Hapus kamar</button><small>Kamar dengan histori penghuni, maintenance, atau import tidak dapat dihapus.</small></div>@endif @endif</details></article>
@empty<div class="empty">Tambahkan kategori, lalu buat kamar pertama.</div>@endforelse</div>
@endif

@if($activeTab==='form-drafts')
<section class="sectionhead"><div><h2>Draft Formulir</h2><p>Formulir yang sudah dikirim dan menunggu pemeriksaan Owner/Admin.</p></div><span class="badge orange">{{ $tenantFormDrafts->count() }} menunggu</span></section><article class="panel tablewrap tenant-form-drafts"><table class="table"><thead><tr><th>Penghuni</th><th>Kamar</th><th>Dikirim</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($tenantFormDrafts as $draft)<tr><td><strong>{{ $draft->response('full_name',$draft->tenant->name) }}</strong><small>{{ $draft->response('phone',$draft->tenant->phone) }}</small></td><td>#{{ $draft->tenant->room->number }}</td><td>{{ $draft->submitted_at->format('d M Y, H:i') }}</td><td><span class="badge orange">Menunggu Approval Draft</span></td><td><a class="btn small" href="{{ route('tenant-form.attachment',$draft->tenant) }}">Periksa Formulir</a></td></tr>@empty<tr><td colspan="5" class="empty">Tidak ada draft yang menunggu approval.</td></tr>@endforelse</tbody></table></article>
@endif

@if($activeTab==='form-builder' && auth()->user()->isOwner())
<section class="sectionhead"><div><h2>Susunan Formulir Penghuni</h2><p>Tambah, ubah, urutkan, atau nonaktifkan section dan pertanyaan. Jawaban lama tetap tersimpan.</p></div></section>
<div class="builder-create-grid">
<article class="panel builder-create"><div class="panelhead"><div><h2>Tambah section</h2><p>Buat kelompok pertanyaan baru.</p></div></div><form class="form" method="post" action="{{ route('form-builder.sections.store') }}">@csrf<div class="field"><label>Nama section</label><input name="title" maxlength="120" required></div><div class="field"><label>Deskripsi</label><input name="description" maxlength="300"></div><div class="field"><label>Urutan</label><input type="number" name="position" min="0" max="999" value="{{ ($formSections->max('position')??0)+1 }}" required></div><button class="btn">Tambah section</button></form></article>
<article class="panel builder-create"><div class="panelhead"><div><h2>Tambah pertanyaan</h2><p>Pertanyaan baru otomatis aktif.</p></div></div><form class="form" method="post" action="{{ route('form-builder.fields.store') }}">@csrf<div class="formgrid"><div class="field"><label>Section</label><select name="tenant_form_section_id" required>@foreach($formSections as $section)<option value="{{ $section->id }}">{{ $section->title }}</option>@endforeach</select></div><div class="field"><label>Tipe jawaban</label><select name="type" required><option value="short_text">Teks singkat</option><option value="long_text">Teks panjang</option><option value="number">Angka</option><option value="date">Tanggal</option><option value="email">Email</option><option value="phone">Nomor telepon</option><option value="select">Dropdown pilihan</option><option value="file">Upload gambar/PDF</option></select></div></div><div class="field"><label>Pertanyaan</label><input name="label" maxlength="120" required></div><div class="formgrid"><div class="field"><label>Placeholder</label><input name="placeholder" maxlength="180"></div><div class="field"><label>Urutan</label><input type="number" name="position" min="0" max="999" value="1" required></div></div><div class="field"><label>Bantuan pengisian</label><input name="help_text" maxlength="300"></div><div class="field"><label>Pilihan dropdown</label><textarea name="options_text" placeholder="Satu pilihan per baris"></textarea></div><label class="builder-check"><input type="checkbox" name="required" value="1"><span>Wajib diisi</span></label><button class="btn">Tambah pertanyaan</button></form></article>
</div>
<div class="form-section-builder">
@foreach($formSections as $section)
<article class="panel builder-section {{ !$section->active?'is-inactive':'' }}"><div class="builder-section-head"><div><span class="badge {{ $section->active?'':'gray' }}">Urutan {{ $section->position }}</span><h2>{{ $section->title }}</h2><p>{{ $section->description }}</p></div><span class="badge {{ $section->active?'':'red' }}">{{ $section->active?'Aktif':'Nonaktif' }}</span></div>
<details class="edit builder-settings"><summary>Edit section</summary><form class="editform builder-section-form" method="post" action="{{ route('form-builder.sections.update',$section) }}">@csrf @method('PATCH')<input name="title" value="{{ $section->title }}" required maxlength="120"><input name="description" value="{{ $section->description }}" maxlength="300"><input type="number" name="position" value="{{ $section->position }}" min="0" max="999" required><label class="builder-check"><input type="checkbox" name="active" value="1" @checked($section->active)><span>Tampilkan section</span></label><button class="btn small">Simpan section</button></form>@if($section->active)<form method="post" action="{{ route('form-builder.sections.destroy',$section) }}" onsubmit="return confirm('Nonaktifkan section ini dari formulir? Jawaban lama tetap tersimpan.')">@csrf @method('DELETE')<button class="btn danger small">Nonaktifkan section</button></form>@endif</details>
<div class="builder-fields">@forelse($section->fields->sortBy('position') as $field)<details class="builder-field {{ !$field->active?'is-inactive':'' }}"><summary><span><b>{{ $field->label }}</b><small>{{ str($field->type)->replace('_',' ')->headline() }} · {{ $field->required?'Wajib':'Opsional' }} · Urutan {{ $field->position }}</small></span><span class="badge {{ $field->active?'':'gray' }}">{{ $field->active?'Aktif':'Nonaktif' }}</span></summary><form class="form" method="post" action="{{ route('form-builder.fields.update',$field) }}">@csrf @method('PATCH')<div class="formgrid"><div class="field"><label>Section</label><select name="tenant_form_section_id" required>@foreach($formSections as $targetSection)<option value="{{ $targetSection->id }}" @selected($field->tenant_form_section_id===$targetSection->id)>{{ $targetSection->title }}</option>@endforeach</select></div><div class="field"><label>Tipe</label><select name="type" required>@foreach(['short_text'=>'Teks singkat','long_text'=>'Teks panjang','number'=>'Angka','date'=>'Tanggal','email'=>'Email','phone'=>'Nomor telepon','select'=>'Dropdown pilihan','file'=>'Upload gambar/PDF'] as $value=>$label)<option value="{{ $value }}" @selected($field->type===$value)>{{ $label }}</option>@endforeach</select></div></div><div class="field"><label>Pertanyaan</label><input name="label" value="{{ $field->label }}" required></div><div class="formgrid"><div class="field"><label>Placeholder</label><input name="placeholder" value="{{ $field->placeholder }}"></div><div class="field"><label>Urutan</label><input type="number" name="position" value="{{ $field->position }}" min="0" max="999" required></div></div><div class="field"><label>Bantuan pengisian</label><input name="help_text" value="{{ $field->help_text }}"></div><div class="field"><label>Pilihan dropdown</label><textarea name="options_text" placeholder="Satu pilihan per baris">{{ implode("\n",$field->options??[]) }}</textarea></div><div class="builder-inline"><label class="builder-check"><input type="checkbox" name="required" value="1" @checked($field->required)><span>Wajib diisi</span></label><label class="builder-check"><input type="checkbox" name="active" value="1" @checked($field->active)><span>Tampilkan pertanyaan</span></label></div><button class="btn small">Simpan pertanyaan</button></form>@if($field->active)<form method="post" action="{{ route('form-builder.fields.destroy',$field) }}" onsubmit="return confirm('Hilangkan pertanyaan ini dari formulir? Jawaban lama tetap tersimpan.')">@csrf @method('DELETE')<button class="btn danger small">Hapus dari formulir</button></form>@endif</details>@empty<div class="empty">Section ini belum punya pertanyaan.</div>@endforelse</div></article>
@endforeach
</div>
@endif

@if($activeTab==='website' && auth()->user()->isOwner())
<section class="sectionhead"><div><h2>Homepage Pemasaran</h2><p>Konten publik di halaman utama. Harga selalu mengikuti kategori kamar di database.</p></div><a class="btn secondary" href="{{ route('home') }}" target="_blank">Lihat homepage ↗</a></section>
<div class="website-grid"><article class="panel website-content"><div class="panelhead"><div><h2>Konten & WhatsApp Admin</h2><p>Gunakan <code>{kategori}</code> dalam template pesan.</p></div></div><form class="form" method="post" action="{{ route('website.update') }}">@csrf @method('PATCH')<div class="field"><label>Judul utama</label><input name="site_hero_title" value="{{ $websiteSettings['site_hero_title'] }}" maxlength="120" required></div><div class="field"><label>Subjudul</label><textarea name="site_hero_subtitle" maxlength="250" required>{{ $websiteSettings['site_hero_subtitle'] }}</textarea></div><div class="field"><label>Tentang RachaqaKost</label><textarea name="site_about" required>{{ $websiteSettings['site_about'] }}</textarea></div><div class="field"><label>Alamat</label><textarea name="site_address" required>{{ $websiteSettings['site_address'] }}</textarea></div><div class="field"><label>Fasilitas</label><textarea name="site_facilities" required placeholder="Satu fasilitas per baris">{{ $websiteSettings['site_facilities'] }}</textarea></div><div class="field"><label>Nomor WhatsApp Admin</label><input name="site_admin_whatsapp" value="{{ $websiteSettings['site_admin_whatsapp'] }}" required></div><div class="field"><label>Template pesan minat</label><textarea name="site_whatsapp_message" required>{{ $websiteSettings['site_whatsapp_message'] }}</textarea></div><button class="btn">Simpan konten homepage</button></form></article>
<div class="website-media-stack"><article class="panel website-logo"><div class="panelhead"><div><h2>Logo & icon website</h2><p>Satu upload otomatis menjadi logo antarmuka 512×512 dan favicon 96×96.</p></div></div>@if($brandLogo)<div class="website-logo-preview"><img src="{{ route('media.public',$brandLogo) }}" alt="Logo RachaqaKost"><span>Logo aktif</span></div><form method="post" action="{{ route('website.logo.destroy') }}" data-confirm="Hapus logo dan kembali memakai logo bawaan?">@csrf @method('DELETE')<button class="btn danger small">Hapus logo</button></form>@else<div class="website-placeholder">Masih memakai logo bawaan “K”</div>@endif<form class="form" method="post" action="{{ route('website.logo') }}" enctype="multipart/form-data">@csrf<div class="field"><label>{{ $brandLogo?'Ganti':'Upload' }} logo</label><input type="file" name="logo" accept="image/jpeg,image/png,image/webp" required><small class="field-help">Background putih di tepi otomatis dibuat transparan. Detail putih di dalam logo tetap dipertahankan. Ukuran 64–4096 px, maksimal 5 MB.</small></div><button class="btn">Simpan & sesuaikan otomatis</button></form></article><article class="panel website-hero"><div class="panelhead"><div><h2>Foto utama</h2><p>JPG, PNG, atau WEBP. Maksimal 5 MB.</p></div></div>@if($homepageHero)<img src="{{ route('media.public',$homepageHero) }}" alt="Foto utama homepage"><form method="post" action="{{ route('website.media.destroy',$homepageHero) }}" onsubmit="return confirm('Hapus foto utama?')">@csrf @method('DELETE')<button class="btn danger small">Hapus foto</button></form>@else<div class="website-placeholder">Belum ada foto utama</div>@endif<form class="form" method="post" action="{{ route('website.hero') }}" enctype="multipart/form-data">@csrf<div class="field"><label>{{ $homepageHero?'Ganti':'Upload' }} foto utama</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></div><button class="btn">Simpan foto</button></form></article></div></div>
<section class="sectionhead"><div><h2>Galeri kategori kamar</h2><p>Tambahkan sampai 8 foto per kategori. Disarankan minimal 5 foto agar calon penghuni mendapat gambaran lengkap.</p></div></section><div class="website-category-grid">@foreach($categories as $category)<article class="panel website-category"><div class="website-category-title"><div><h2>{{ $category->name }}</h2><p>Rp {{ number_format($category->monthly_price,0,',','.') }} / bulan</p></div><span class="badge {{ $category->photos->count()<5?'orange':'' }}">{{ $category->photos->count() }}/8 foto</span></div><div class="website-thumbs">@forelse($category->photos as $photo)<div><img src="{{ route('media.public',$photo) }}" alt="{{ $category->name }}"><form method="post" action="{{ route('website.media.destroy',$photo) }}" onsubmit="return confirm('Hapus foto ini?')">@csrf @method('DELETE')<button aria-label="Hapus foto">×</button></form></div>@empty<div class="website-placeholder">Belum ada foto</div>@endforelse</div>@if($category->photos->count()<8)<form class="form" method="post" action="{{ route('website.category-photos',$category) }}" enctype="multipart/form-data">@csrf<div class="field"><label>Tambah foto</label><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple required><small class="field-help">Pilih maksimal {{ 8-$category->photos->count() }} file.</small></div><button class="btn small">Upload foto</button></form>@endif</article>@endforeach</div>
@endif

@if($activeTab==='tenants')
<section class="sectionhead"><div><h2>Penghuni aktif</h2><p>{{ $tenants->count() }} penghuni sedang tinggal.</p></div><div class="actions">@if(auth()->user()->isOwner())<button class="btn secondary" data-open="whatsappTemplateModal">Template WA Reminder</button><button class="btn secondary" data-open="tenantFormTemplateModal">Template WA Formulir</button>@endif<button class="btn" data-open="tenantModal">+ Check-in</button></div></section>
<article class="panel tablewrap"><table class="table tenant-table"><thead><tr><th>Penghuni</th><th>Kamar</th><th>Kontak</th><th>Mulai tinggal</th><th>Jatuh tempo</th><th>Status Formulir</th><th>Aksi</th></tr></thead><tbody>
@forelse($tenants as $t)
@php($waUrl=$t->whatsappUrl($whatsappTemplate)) @php($formWaUrl=$t->formWhatsappUrl($tenantFormWhatsAppTemplate))
<tr><td><strong>{{ $t->name }}</strong><small>{{ $t->identity_number?:'Identitas belum diisi' }}</small></td><td><strong>#{{ $t->room->number }}</strong><small>{{ $t->room->category->name }} · {{ $t->billingCycleLabel() }}</small></td><td>{{ $t->phone }}</td><td>{{ $t->move_in->format('d M Y') }}</td><td><span class="badge {{ $t->isOverdue()?'red':($t->next_due->lte(now()->addDays(7))?'orange':'') }}">{{ ($t->isOverdue()||$t->isDueToday())?$t->dueStatusLabel():$t->next_due->format('d M Y') }}</span>@if($t->isOverdue())<small>Jatuh tempo {{ $t->next_due->format('d M Y') }}</small>@endif</td><td><span class="badge {{ $t->formStatusBadge() }}">{{ $t->formStatusLabel() }}</span><div class="tenant-form-actions">@if($t->tenantForm)<a class="btn secondary small" href="{{ route('tenant-form.attachment',$t) }}">Attachment Formulir</a>@endif @if(!$t->tenantForm||$t->tenantForm->status==='REVISION')@if($formWaUrl)<a class="wa-button compact" href="{{ $formWaUrl }}" target="_blank" rel="noopener noreferrer">WA Formulir</a>@endif @endif</div></td><td><div class="table-actions">
@if($waUrl)<a class="wa-button" href="{{ $waUrl }}" target="_blank" rel="noopener noreferrer">Chat WA</a>@else<span class="badge red">Nomor tidak valid</span>@endif
<button type="button" class="btn secondary small tenant-edit-button" data-action="{{ route('tenants.update',$t) }}" data-active="1" data-room="{{ $t->room_id }}" data-cycle="{{ $t->billing_cycle }}" data-name="{{ $t->name }}" data-phone="{{ $t->phone }}" data-identity="{{ $t->identity_number }}" data-move-in="{{ $t->move_in->toDateString() }}" data-next-due="{{ $t->next_due->toDateString() }}" data-move-out="">Edit</button>
<form method="post" action="{{ route('tenants.checkout',$t) }}">@csrf @method('PATCH')<input type="hidden" name="move_out" value="{{ today()->toDateString() }}"><button class="btn secondary small">Check-out</button></form>
</div></td></tr>
@empty<tr><td colspan="7" class="empty">Belum ada penghuni aktif.</td></tr>@endforelse
</tbody></table></article>
@if($tenantHistory->isNotEmpty())
<div style="height:18px"></div><article class="panel"><div class="panelhead"><div><h2>Riwayat check-out</h2><p>Data lama tetap tersimpan dan dapat dikoreksi.</p></div></div><div class="tablewrap"><table class="table"><thead><tr><th>Nama</th><th>Kamar terakhir</th><th>Masuk</th><th>Keluar</th><th>Aksi</th></tr></thead><tbody>
@foreach($tenantHistory as $t)
<tr><td><strong>{{ $t->name }}</strong><small>{{ $t->phone }} · {{ $t->billingCycleLabel() }}</small></td><td>#{{ $t->room->number }}</td><td>{{ $t->move_in->format('d M Y') }}</td><td>{{ $t->move_out?->format('d M Y') }}</td><td>@if($t->tenantForm)<a class="btn secondary small" href="{{ route('tenant-form.attachment',$t) }}">Attachment Formulir</a>@else<span class="badge gray">Formulir Belum Diisi</span>@endif</td></tr>
@endforeach
</tbody></table></div></article>
@endif
@endif

@if($activeTab==='payments')
@include('partials.payment-ledger')
@endif

@if($activeTab==='expenses')
<section class="sectionhead"><div><h2>Kategori pengeluaran</h2><p>Atur fungsi biaya serta klasifikasi fixed dan variable cost.</p></div>@if(auth()->user()->isOwner())<button class="btn secondary" data-open="expenseCategoryModal">+ Kategori</button>@endif</section><div class="expense-category-grid">@foreach($expenseCategories as $ec)<article class="expense-category-card" style="--accent:{{ $ec->color }}"><div><i></i><b>{{ $ec->name }}</b><span class="badge {{ $ec->cost_type==='DIRECT'?'orange':'gray' }}">{{ $ec->cost_type==='DIRECT'?'Langsung':'Operasional' }}</span><span class="badge {{ $ec->cost_behavior==='VARIABLE'?'blue':'gray' }}">{{ $ec->cost_behavior==='VARIABLE'?'Variabel':'Tetap' }}</span>@if($ec->is_system)<span class="badge gray">Sistem</span>@endif</div>@if(auth()->user()->isOwner())<details class="edit"><summary>Atur kategori</summary><form class="editform" method="post" action="{{ route('expense-categories.update',$ec) }}">@csrf @method('PATCH')<input name="name" value="{{ $ec->name }}" @readonly($ec->is_system) required><select name="cost_type" required><option value="DIRECT" @selected($ec->cost_type==='DIRECT')>Biaya langsung</option><option value="OPERATING" @selected($ec->cost_type==='OPERATING')>Biaya operasional</option></select><select name="cost_behavior" required><option value="VARIABLE" @selected($ec->cost_behavior==='VARIABLE')>Variable cost — berubah mengikuti aktivitas</option><option value="FIXED" @selected($ec->cost_behavior==='FIXED')>Fixed cost — keluar secara berkala</option></select><input type="color" name="color" value="{{ $ec->color }}" required><button class="btn small">Simpan</button></form>@unless($ec->is_system)<form method="post" action="{{ route('expense-categories.destroy',$ec) }}">@csrf @method('DELETE')<button class="btn danger small" style="margin-top:7px">Hapus</button></form>@endunless</details>@endif</article>@endforeach</div><div style="height:22px"></div>
@include('partials.expense-ledger')
@endif

@if($activeTab==='maintenance')
<section class="sectionhead"><div><h2>Riwayat maintenance</h2><p>Setiap catatan langsung terhubung ke kamar dan pengeluaran bulanan.</p></div><button class="btn" data-open="maintenanceModal">+ Catat maintenance</button></section><article class="panel tablewrap"><table class="table"><thead><tr><th>Kamar</th><th>Maintenance</th><th>Tanggal</th><th>Biaya</th></tr></thead><tbody>@forelse($maintenances as $m)<tr><td><strong>#{{ $m->room->number }}</strong></td><td><strong>{{ $m->title }}</strong><small>{{ $m->notes }}</small></td><td>{{ $m->reported_at->format('d M Y') }}</td><td>Rp {{ number_format($m->cost,0,',','.') }}</td></tr>@empty<tr><td colspan="4" class="empty">Belum ada riwayat maintenance.</td></tr>@endforelse</tbody></table></article>
@endif

@if($activeTab==='users'&&auth()->user()->isOwner())
<section class="sectionhead"><div><h2>User Owner & Penjaga</h2><p>Owner mengatur harga dan akses; Penjaga fokus operasional.</p></div><button class="btn" data-open="userModal">+ Tambah user</button></section><article class="panel tablewrap"><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Bergabung</th><th>Atur</th></tr></thead><tbody>@foreach($users as $u)<tr><td><strong>{{ $u->name }}</strong></td><td>{{ $u->email }}</td><td><span class="badge {{ $u->role==='OWNER'?'':'gray' }}">{{ $u->role }}</span></td><td>{{ $u->created_at?->format('d M Y') }}</td><td><details><summary>Edit</summary><form class="editform" method="post" action="{{ route('users.update',$u) }}">@csrf @method('PATCH')<input name="name" value="{{ $u->name }}" required><select name="role"><option value="OWNER" @selected($u->role==='OWNER')>Owner</option><option value="PENJAGA" @selected($u->role==='PENJAGA')>Penjaga</option></select><input type="password" name="password" placeholder="Password baru (opsional)"><input type="password" name="password_confirmation" placeholder="Ulangi password"><button class="btn small">Simpan akses</button></form></details></td></tr>@endforeach</tbody></table></article>
@endif
</main><nav class="mobile">@foreach($tabs as $key=>$tab)@if(!in_array($key,$ownerOnlyTabs,true)||auth()->user()->isOwner())<a href="{{ route('dashboard',['tab'=>$key]) }}" class="{{ $activeTab===$key?'active':'' }}"><b>{{ $tab[0] }}</b>{{ $tab[1] }}</a>@endif @endforeach @if(auth()->user()->isOwner())<a href="{{ route('finance') }}"><b>Rp</b>Keuangan</a><a href="{{ route('imports.index') }}"><b>⇧</b>Import</a>@endif</nav></div>

<dialog class="modal" id="paymentModal"><div class="modalhead"><div><h2>Catat pembayaran</h2><p>Catat sewa harian, mingguan, atau bulanan.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('payments.store') }}">@csrf<div class="field"><label>Jenis pencatatan</label><select name="payment_mode" id="paymentMode" required><option value="REGULAR">Pembayaran Reguler</option><option value="HISTORICAL">Pembayaran Historis</option></select><small class="field-help" id="paymentModeHelp">Gunakan reguler untuk pembayaran berjalan.</small></div><div class="field"><label>Penghuni</label><select name="tenant_id" id="paymentTenant" required><option value="">Pilih penghuni</option>@foreach($paymentTenants as $t)<option value="{{ $t->id }}" data-active="{{ $t->active?'1':'0' }}" data-due="{{ $t->next_due->toDateString() }}" data-cycle="{{ $t->billing_cycle }}" data-daily="{{ (int)$t->room->category->daily_price }}" data-weekly="{{ (int)$t->room->category->weekly_price }}" data-monthly="{{ (int)$t->room->category->monthly_price }}">#{{ $t->room->number }} · {{ $t->name }} · {{ $t->active?'Aktif':'Check-out' }}</option>@endforeach</select></div><div class="formgrid"><div class="field"><label>Siklus pembayaran</label><select name="billing_cycle" id="paymentBillingCycle" required><option value="DAILY">Harian</option><option value="WEEKLY">Mingguan</option><option value="MONTHLY" selected>Bulanan</option></select><small class="field-help">Untuk pembayaran reguler, pilihan ini juga menjadi siklus penghuni berikutnya.</small></div><div class="field historical-payment-fields" id="historicalPaymentFields" hidden><label>Periode mulai histori</label><input type="date" name="period_start" id="historicalPeriodStart" value="{{ today()->startOfMonth()->toDateString() }}"></div></div><div class="formgrid"><div class="field"><label>Nominal</label><div class="currency-input"><span>Rp</span><input type="text" name="amount" data-currency inputmode="numeric" autocomplete="off" placeholder="0" required></div></div><div class="field"><label id="paymentPeriodsLabel">Jumlah periode</label><input type="number" name="periods" id="paymentPeriods" value="1" min="1" max="365" required></div><div class="field"><label>Tanggal bayar</label><input type="date" name="paid_at" value="{{ today()->toDateString() }}" required></div><div class="field"><label>Metode</label><select name="method"><option>Transfer</option><option>QRIS</option><option>Cash</option></select></div></div><div class="field"><label>Periode tagihan</label><input id="paymentPeriod" value="Pilih penghuni terlebih dahulu" readonly aria-readonly="true"><small class="field-help" id="paymentCycleHelp">Dihitung otomatis dan tidak dapat diedit.</small></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Simpan pembayaran</button></div></form></dialog>
<dialog class="modal" id="expenseModal"><div class="modalhead"><div><h2>Catat pengeluaran</h2><p>Masuk ke arus kas bulan berjalan.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('expenses.store') }}">@csrf<div class="field"><label>Nama pengeluaran</label><input name="title" required></div><div class="formgrid"><div class="field"><label>Kategori</label><select name="category" required>@foreach($expenseCategories as $ec)<option value="{{ $ec->name }}">{{ $ec->name }}</option>@endforeach</select></div><div class="field"><label>Nominal</label><div class="currency-input"><span>Rp</span><input type="text" name="amount" data-currency inputmode="numeric" autocomplete="off" placeholder="0" required></div></div><div class="field"><label>Tanggal</label><input type="date" name="spent_at" value="{{ today()->toDateString() }}" required></div></div><div class="field"><label>Catatan</label><textarea name="notes"></textarea></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Simpan</button></div></form></dialog>
@if(auth()->user()->isOwner())<dialog class="modal" id="expenseCategoryModal"><div class="modalhead"><div><h2>Kategori pengeluaran baru</h2><p>Klasifikasi dipakai untuk laporan laba dan struktur biaya umum.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('expense-categories.store') }}">@csrf<div class="field"><label>Nama kategori</label><input name="name" maxlength="60" required></div><div class="field"><label>Fungsi biaya</label><select name="cost_type" required><option value="OPERATING">Biaya operasional</option><option value="DIRECT">Biaya langsung</option></select><small class="field-help">Biaya langsung dipakai menghitung gross profit; biaya operasional dipakai setelah gross profit.</small></div><div class="field"><label>Perilaku biaya</label><select name="cost_behavior" required><option value="FIXED">Fixed cost — keluar secara berkala</option><option value="VARIABLE">Variable cost — berubah mengikuti aktivitas</option></select><small class="field-help">Klasifikasi ini tidak dikaitkan dengan okupansi kamar.</small></div><div class="field"><label>Warna penanda</label><input type="color" name="color" value="#DF8A42" required></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Tambah kategori</button></div></form></dialog>@endif
<dialog class="modal" id="tenantModal"><div class="modalhead"><div><h2>Check-in penghuni</h2><p>Pilih kamar kosong dan siklus sewa yang berlaku.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('tenants.store') }}">@csrf<div class="field"><label>Kamar</label><select name="room_id" id="tenantRoom" required><option value="">Pilih kamar kosong</option>@foreach($rooms->where('status','KOSONG') as $r)<option value="{{ $r->id }}" data-daily="{{ (int)$r->category->daily_price }}" data-weekly="{{ (int)$r->category->weekly_price }}" data-monthly="{{ (int)$r->category->monthly_price }}">#{{ $r->number }} · {{ $r->category->name }}</option>@endforeach</select></div><div class="field"><label>Siklus sewa</label><select name="billing_cycle" id="tenantBillingCycle" required><option value="DAILY">Harian</option><option value="WEEKLY">Mingguan</option><option value="MONTHLY" selected>Bulanan</option></select><small class="field-help" id="tenantRatePreview">Pilih kamar untuk melihat tarif.</small></div><div class="formgrid"><div class="field"><label>Nama lengkap</label><input name="name" required></div><div class="field"><label>No. HP</label><input name="phone" required></div><div class="field"><label>No. identitas</label><input name="identity_number"></div><div class="field"><label>Tanggal masuk</label><input type="date" name="move_in" id="tenantMoveIn" value="{{ today()->toDateString() }}" required></div><div class="field"><label>Jatuh tempo pertama</label><input type="date" name="next_due" id="tenantNextDue" value="{{ today()->addMonthNoOverflow()->toDateString() }}" required></div></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Check-in</button></div></form></dialog>
<dialog class="modal" id="tenantEditModal"><div class="modalhead"><div><h2>Edit data penghuni</h2><p id="tenantEditSubtitle">Perbarui informasi tanpa menghapus histori.</p></div><button class="close" data-close>×</button></div><form class="form" id="tenantEditForm" method="post">@csrf @method('PATCH')<div class="field"><label>Kamar</label><select name="room_id" id="tenantEditRoom" required>@foreach($rooms as $r)<option value="{{ $r->id }}" data-status="{{ $r->status }}">#{{ $r->number }} · {{ $r->category->name }} · {{ str($r->status)->headline() }}</option>@endforeach</select><small class="field-help" id="tenantEditRoomHelp">Untuk penghuni aktif, hanya kamar kosong yang dapat menjadi tujuan pindah.</small></div><div class="field"><label>Siklus sewa</label><select name="billing_cycle" required><option value="DAILY">Harian</option><option value="WEEKLY">Mingguan</option><option value="MONTHLY">Bulanan</option></select></div><div class="formgrid"><div class="field"><label>Nama lengkap</label><input name="name" required maxlength="120"></div><div class="field"><label>No. HP / WhatsApp</label><input name="phone" required maxlength="30"></div><div class="field"><label>No. identitas</label><input name="identity_number" maxlength="40"></div><div class="field"><label>Tanggal masuk</label><input type="date" name="move_in" required></div><div class="field" id="tenantEditDueField"><label>Jatuh tempo berikutnya</label><input type="date" name="next_due" required></div><div class="field" id="tenantEditOutField" hidden><label>Tanggal keluar</label><input type="date" name="move_out"></div></div><div class="tenant-edit-status" id="tenantEditStatus"></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Simpan perubahan</button></div></form></dialog>
@include('partials.maintenance-modal')
<dialog class="modal" id="roomModal"><div class="modalhead"><div><h2>Tambah kamar</h2><p>Kamar baru otomatis kosong.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('rooms.store') }}">@csrf<div class="formgrid"><div class="field"><label>Nomor kamar</label><input name="number" required></div><div class="field"><label>Lantai</label><input type="number" name="floor" value="1" min="1" required></div></div><div class="field"><label>Kategori</label><select name="room_category_id" required>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Tambah kamar</button></div></form></dialog>
@if(auth()->user()->isOwner())<dialog class="modal" id="categoryModal"><div class="modalhead"><div><h2>Kategori baru</h2><p>Atur tarif sewa harian, mingguan, dan bulanan.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('categories.store') }}">@csrf<div class="field"><label>Nama kategori</label><input name="name" required></div><div class="formgrid"><div class="field"><label>Harga harian</label><div class="currency-input"><span>Rp</span><input type="text" name="daily_price" data-currency inputmode="numeric" value="0" required></div></div><div class="field"><label>Harga mingguan</label><div class="currency-input"><span>Rp</span><input type="text" name="weekly_price" data-currency inputmode="numeric" value="0" required></div></div></div><div class="field"><label>Harga bulanan</label><div class="currency-input"><span>Rp</span><input type="text" name="monthly_price" data-currency inputmode="numeric" autocomplete="off" placeholder="0" required></div></div><div class="field"><label>Warna penanda</label><input type="color" name="color" value="#2C7668"></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Buat kategori</button></div></form></dialog>
<dialog class="modal" id="whatsappTemplateModal"><div class="modalhead"><div><h2>Template follow-up WhatsApp</h2><p>Pesan terisi otomatis sesuai data penghuni dan jatuh tempo.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('settings.whatsapp-template') }}">@csrf @method('PATCH')<div class="field"><label>Isi pesan</label><textarea name="template" class="template-textarea" maxlength="1500" required>{{ $whatsappTemplate }}</textarea><small class="field-help">Placeholder: <code>{nama}</code>, <code>{kamar}</code>, <code>{kategori}</code>, <code>{nominal}</code>, <code>{siklus}</code>, <code>{jatuh_tempo}</code>, <code>{status}</code>.</small></div><div class="template-preview"><b>Contoh hasil</b><p id="whatsappTemplatePreview"></p></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Simpan template</button></div></form></dialog>
<dialog class="modal" id="tenantFormTemplateModal"><div class="modalhead"><div><h2>Template WA Formulir</h2><p>Pesan otomatis untuk mengirim link formulir unik penghuni.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('settings.tenant-form-whatsapp-template') }}">@csrf @method('PATCH')<div class="field"><label>Isi pesan</label><textarea name="template" class="template-textarea" maxlength="1500" required>{{ $tenantFormWhatsAppTemplate }}</textarea><small class="field-help">Placeholder: <code>{nama}</code>, <code>{kamar}</code>, <code>{link_formulir}</code>, <code>{status_formulir}</code>.</small></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Simpan template</button></div></form></dialog>
<dialog class="modal" id="userModal"><div class="modalhead"><div><h2>Tambah user</h2><p>Buat akses Owner atau Penjaga.</p></div><button class="close" data-close>×</button></div><form class="form" method="post" action="{{ route('users.store') }}">@csrf<div class="field"><label>Nama</label><input name="name" required></div><div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field"><label>Role</label><select name="role"><option value="PENJAGA">Penjaga</option><option value="OWNER">Owner</option></select></div><div class="formgrid"><div class="field"><label>Password awal</label><input type="password" name="password" minlength="10" required></div><div class="field"><label>Ulangi password</label><input type="password" name="password_confirmation" minlength="10" required></div></div><div class="modalfoot"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn">Tambah user</button></div></form></dialog>@endif
<script src="{{ asset('assets/rachaqakost.js') }}?v=20260904-maintenance-entry"></script><script src="{{ asset('assets/confirm-actions.js') }}?v=20260905-3"></script></body></html>
