<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Review Import #{{ $batch->id }} — RachaqaKost</title><link rel="stylesheet" href="{{ asset('assets/rachaqakost.css') }}"><link rel="stylesheet" href="{{ asset('assets/rachaqakost-fixes.css') }}?v=20260817-import"></head>
<body>
@php($draft=$batch->status==='DRAFT')
<div class="shell"><aside class="sidebar"><div class="brand"><span class="brandmark">K</span><div><b>RachaqaKost</b><small>Operational OS</small></div></div><nav class="nav"><a href="{{ route('dashboard') }}"><span class="ico">⌂</span>Ringkasan</a><a href="{{ route('dashboard',['tab'=>'payments']) }}"><span class="ico">↗</span>Pembayaran</a><a href="{{ route('dashboard',['tab'=>'expenses']) }}"><span class="ico">↘</span>Pengeluaran</a><div class="nav-separator"></div><a href="{{ route('finance') }}"><span class="ico">Rp</span>Keuangan</a><a href="{{ route('imports.index') }}" class="active"><span class="ico">⇧</span>Import Data</a></nav><div class="profile"><b>{{ auth()->user()->name }}</b><small>Owner / Admin</small><form method="post" action="{{ route('logout') }}">@csrf<button class="logout">Keluar dari workspace</button></form></div></aside>
<main class="main import-main"><header class="top import-top"><div><a class="back-link" href="{{ route('imports.index') }}">← Semua batch</a><h1>Review batch #{{ str_pad($batch->id,4,'0',STR_PAD_LEFT) }}</h1><p>{{ $batch->source_type==='IMAGE'?'Hasil pembacaan foto AI':'Data dari CSV' }} · {{ collect($batch->original_names)->join(', ') }}</p></div><span class="batch-status {{ strtolower($batch->status) }}">{{ match($batch->status){'DRAFT'=>'Perlu review','COMPLETED'=>'Sudah masuk','FAILED'=>'Gagal'} }}</span></header>
@if(session('success'))<div class="toast">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="toast error">{{ $errors->first() }}</div>@endif

<section class="import-review-stats"><article><span>Total terbaca</span><strong>{{ $batch->total_rows }}</strong></article><article><span>Siap import</span><strong>{{ $batch->valid_rows }}</strong></article><article><span>Sudah masuk</span><strong>{{ $batch->imported_rows }}</strong></article><article><span>Dibuat oleh</span><strong>{{ $batch->uploader->name }}</strong></article></section>
@if($batch->undo_count > 0)<section class="import-undo-note"><span>↶</span><div><b>Batch ini pernah di-undo {{ $batch->undo_count }} kali</b><p>Terakhir {{ $batch->last_undone_at?->translatedFormat('d F Y H:i') }} oleh {{ $batch->undoer?->name ?? 'user yang sudah dihapus' }}. Audit ini tetap tersimpan setelah commit ulang.</p></div></section>@endif
@if($draft)<section class="review-instruction"><b>Periksa sebelum commit</b><p>Baris merah wajib dikoreksi atau dimatikan centangnya. Khusus pembayaran, pastikan penghuni dan periode awal benar. Commit tidak akan mengubah jatuh tempo.</p></section>@endif

<form method="post" action="{{ route('imports.update',$batch) }}" class="import-review-form">@csrf @method('PATCH')
@forelse($batch->rows as $row)
    <article class="import-row-card {{ empty($row->validation_errors)?'valid':'invalid' }}" data-import-row>
        <div class="import-row-head"><label class="row-selector"><input type="hidden" name="rows[{{ $row->id }}][selected]" value="0"><input type="checkbox" name="rows[{{ $row->id }}][selected]" value="1" @checked($row->selected) @disabled(!$draft)> <span>Baris {{ $row->row_number }}</span></label><div class="row-health">@if($row->confidence!==null)<span>AI {{ number_format((float)$row->confidence,0) }}%</span>@endif<span class="{{ empty($row->validation_errors)?'ok':'bad' }}">{{ empty($row->validation_errors)?'Siap import':'Perlu koreksi' }}</span></div></div>
        @if(!empty($row->validation_errors))<div class="row-errors">@foreach($row->validation_errors as $error)<span>• {{ $error }}</span>@endforeach</div>@endif
        <div class="import-row-grid">
            <div class="field"><label>Jenis</label><select name="rows[{{ $row->id }}][transaction_type]" data-import-type @disabled(!$draft)><option value="PAYMENT" @selected($row->transaction_type==='PAYMENT')>Pendapatan / pembayaran</option><option value="EXPENSE" @selected($row->transaction_type==='EXPENSE')>Pengeluaran</option></select></div>
            <div class="field payment-only"><label>Penghuni</label><select name="rows[{{ $row->id }}][tenant_id]" @disabled(!$draft)><option value="">Pilih penghuni</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected($row->tenant_id===$tenant->id)>#{{ $tenant->room->number }} · {{ $tenant->name }} · {{ $tenant->active?'Aktif':'Check-out' }}</option>@endforeach</select></div>
            <div class="field expense-only"><label>Kategori pengeluaran</label><select name="rows[{{ $row->id }}][expense_category]" @disabled(!$draft)><option value="">Pilih kategori</option>@foreach($expenseCategories as $category)<option value="{{ $category->name }}" @selected($row->expense_category===$category->name)>{{ $category->name }}</option>@endforeach</select></div>
            <div class="field"><label>Tanggal transaksi</label><input type="date" name="rows[{{ $row->id }}][transaction_date]" value="{{ $row->transaction_date?->toDateString() }}" @readonly(!$draft)></div>
            <div class="field"><label>Nominal</label><div class="currency-input"><span>Rp</span><input type="text" name="rows[{{ $row->id }}][amount]" data-currency inputmode="numeric" value="{{ $row->amount?number_format((float)$row->amount,0,',','.') : '' }}" @readonly(!$draft)></div></div>
            <div class="field payment-only"><label>Siklus</label><select name="rows[{{ $row->id }}][billing_cycle]" @disabled(!$draft)><option value="DAILY" @selected($row->billing_cycle==='DAILY')>Harian</option><option value="WEEKLY" @selected($row->billing_cycle==='WEEKLY')>Mingguan</option><option value="MONTHLY" @selected($row->billing_cycle==='MONTHLY')>Bulanan</option></select></div>
            <div class="field payment-only"><label>Jumlah periode</label><input type="number" name="rows[{{ $row->id }}][period_count]" value="{{ $row->period_count }}" min="1" max="365" @readonly(!$draft)></div>
            <div class="field payment-only"><label>Periode mulai</label><input type="date" name="rows[{{ $row->id }}][period_start]" value="{{ $row->period_start?->toDateString() }}" @readonly(!$draft)></div>
            <div class="field payment-only"><label>Metode</label><select name="rows[{{ $row->id }}][method]" @disabled(!$draft)><option value="Transfer" @selected($row->method==='Transfer')>Transfer</option><option value="QRIS" @selected($row->method==='QRIS')>QRIS</option><option value="Cash" @selected($row->method==='Cash')>Cash</option></select></div>
            <div class="field expense-only import-span-2"><label>Nama pengeluaran</label><input name="rows[{{ $row->id }}][title]" value="{{ $row->title }}" maxlength="150" @readonly(!$draft)></div>
            <div class="field import-span-2"><label>Catatan / hasil baca</label><input name="rows[{{ $row->id }}][notes]" value="{{ $row->notes }}" maxlength="2000" @readonly(!$draft)></div>
        </div>
    </article>
@empty<div class="empty">Batch tidak memiliki baris.</div>@endforelse
@if($draft)<div class="import-savebar"><div><b>Simpan koreksi lebih dulu</b><small>Validasi akan dijalankan ulang untuk semua baris.</small></div><button class="btn secondary">Simpan & validasi</button></div>@endif
</form>

@if($draft)<section class="import-commit-panel"><div><span class="eyebrow">FINAL STEP</span><h2>Masukkan ke pembukuan</h2><p>Hanya baris tercentang dan valid yang akan dibuat. Setelah commit, batch tetap dapat di-undo tanpa menyentuh transaksi manual atau jatuh tempo.</p></div><form method="post" action="{{ route('imports.commit',$batch) }}" onsubmit="return confirm('Import seluruh baris terpilih yang valid?')">@csrf<button class="btn" @disabled($batch->valid_rows===0)>Commit {{ $batch->valid_rows }} transaksi</button></form><form method="post" action="{{ route('imports.destroy',$batch) }}" onsubmit="return confirm('Hapus draft batch ini?')">@csrf @method('DELETE')<button class="btn danger">Hapus draft</button></form></section>@elseif($batch->status==='COMPLETED')<section class="import-completed import-completed-with-action"><span>✓</span><div><b>{{ $batch->imported_rows }} transaksi sudah masuk</b><p>Di-commit {{ $batch->committed_at?->translatedFormat('d F Y H:i') }} dan tersimpan sebagai transaksi historis.</p></div><form method="post" action="{{ route('imports.undo',$batch) }}" onsubmit="return confirm('Undo batch ini? Semua pembayaran dan pengeluaran yang dibuat oleh batch ini akan dihapus dari pembukuan. Transaksi manual dan jatuh tempo tidak akan berubah.')">@csrf<button class="btn danger import-undo-button">↶ Undo import</button></form></section><section class="import-undo-explainer"><b>Apa yang terjadi saat undo?</b><p>Transaksi milik batch ini dihapus secara atomik, lalu batch kembali menjadi draft agar dapat dikoreksi dan di-commit ulang. Riwayat undo tetap dicatat.</p></section>@else<section class="import-completed import-failed"><span>!</span><div><b>Batch gagal diproses</b><p>{{ $batch->error_message }}</p></div><form method="post" action="{{ route('imports.destroy',$batch) }}">@csrf @method('DELETE')<button class="btn danger small">Hapus</button></form></section>@endif
</main><nav class="mobile"><a href="{{ route('dashboard') }}"><b>⌂</b>Ringkasan</a><a href="{{ route('finance') }}"><b>Rp</b>Keuangan</a><a href="{{ route('imports.index') }}" class="active"><b>⇧</b>Import</a></nav></div>
<script src="{{ asset('assets/rachaqakost.js') }}?v=20260817-import"></script></body></html>
