<section class="waiting-admin-summary">
    <article><span>Belum di-follow-up</span><strong>{{ (int)($waitingCounts['NEW']??0) }}</strong></article>
    <article><span>Sudah di-follow-up</span><strong>{{ (int)($waitingCounts['FOLLOWED_UP']??0) }}</strong></article>
    <article><span>Diarsipkan</span><strong>{{ (int)($waitingCounts['ARCHIVED']??0) }}</strong></article>
</section>
<section class="sectionhead waiting-heading"><div><h2>Waiting List Kamar</h2><p>Kelola calon penghuni berdasarkan kategori, tanggal masuk, dan status tindak lanjut.</p></div>@if(auth()->user()->isOwner())<div class="waiting-heading-actions"><button class="btn secondary" data-open="waitingTemplateModal">Template Penawaran</button><button class="btn" data-open="waitingFieldModal">+ Pertanyaan</button></div>@endif</section>
<form class="waiting-filters panel" method="get" action="{{ route('dashboard') }}">
    <input type="hidden" name="tab" value="waiting-list">
    <label><span>Status follow-up</span><select name="waiting_status"><option value="ACTIVE" @selected($waitingStatus==='ACTIVE')>Daftar aktif</option><option value="NEW" @selected($waitingStatus==='NEW')>Belum di-follow-up</option><option value="FOLLOWED_UP" @selected($waitingStatus==='FOLLOWED_UP')>Sudah di-follow-up</option><option value="ARCHIVED" @selected($waitingStatus==='ARCHIVED')>Diarsipkan</option><option value="ALL" @selected($waitingStatus==='ALL')>Semua status</option></select></label>
    <label><span>Submit dari</span><input type="date" name="waiting_from" value="{{ $waitingFrom }}"></label>
    <label><span>Sampai</span><input type="date" name="waiting_to" value="{{ $waitingTo }}"></label>
    <button class="btn">Terapkan</button><a class="btn secondary" href="{{ route('dashboard',['tab'=>'waiting-list']) }}">Reset</a>
</form>
<article class="panel tablewrap"><table class="table waiting-table"><thead><tr><th>Calon penghuni</th><th>Minat kamar</th><th>Batas follow-up</th><th>Tanggal submit</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($waitingEntries as $entry)
<tr><td><strong>{{ $entry->name }}</strong><small>{{ $entry->phone }}</small>@if(count($entry->responses??[])>5)<details class="waiting-response"><summary>Lihat jawaban tambahan</summary>@foreach($entry->responses as $key=>$answer)@unless(in_array($key,['name','phone','room_category','preferred_floor','followup_until'],true))<span><b>{{ $waitingListFields->firstWhere('key',$key)?->label??str($key)->headline() }}</b> {{ is_array($answer)?implode(', ',$answer):$answer }}</span>@endunless @endforeach</details>@endif</td><td><strong>{{ $entry->categoryLabel() }}</strong><small>Preferensi lantai {{ $entry->preferred_floor }}</small></td><td>{{ $entry->followup_until->translatedFormat('F Y') }}</td><td>{{ $entry->submitted_at->format('d M Y, H:i') }}</td><td><span class="badge {{ $entry->statusBadge() }}">{{ $entry->statusLabel() }}</span>@if($entry->followed_up_at)<small>{{ $entry->followed_up_at->format('d M Y, H:i') }} · {{ $entry->followupUser?->name }}</small>@endif</td><td><div class="table-actions">@if($entry->status!=='ARCHIVED')<form method="post" action="{{ route('waiting-lists.followup',$entry) }}" target="_blank">@csrf<button class="wa-button compact">Follow-up WhatsApp</button></form>@if($entry->followed_up_at)<form method="post" action="{{ route('waiting-lists.archive',$entry) }}" onsubmit="return confirm('Arsipkan waiting list ini karena sudah tidak tertarik?')">@csrf @method('PATCH')<button class="btn secondary small">Arsipkan</button></form>@endif @else<form method="post" action="{{ route('waiting-lists.restore',$entry) }}">@csrf @method('PATCH')<button class="btn secondary small">Kembalikan</button></form>@endif</div></td></tr>
@empty<tr><td colspan="6" class="empty">Tidak ada waiting list untuk filter ini.</td></tr>@endforelse
</tbody></table></article>
@if(method_exists($waitingEntries,'hasPages')&&$waitingEntries->hasPages())<nav class="waiting-pagination">@if($waitingEntries->onFirstPage())<span>← Sebelumnya</span>@else<a href="{{ $waitingEntries->previousPageUrl() }}">← Sebelumnya</a>@endif <b>Halaman {{ $waitingEntries->currentPage() }} dari {{ $waitingEntries->lastPage() }}</b> @if($waitingEntries->hasMorePages())<a href="{{ $waitingEntries->nextPageUrl() }}">Berikutnya →</a>@else<span>Berikutnya →</span>@endif</nav>@endif
@if(auth()->user()->isOwner())
<details class="panel waiting-builder"><summary><div><b>Atur Form Waiting List</b><small>Edit label, bantuan, urutan, dan pertanyaan tambahan.</small></div><span>Kelola Formulir⌄</span></summary><div class="waiting-builder-list">@foreach($waitingListFields as $field)<details class="builder-field {{ !$field->active?'is-inactive':'' }}"><summary><span><b>{{ $field->label }}</b><small>{{ $field->is_system?'Pertanyaan bawaan':'Pertanyaan tambahan' }} · Urutan {{ $field->position }}</small></span><span class="badge {{ $field->active?'':'gray' }}">{{ $field->active?'Aktif':'Nonaktif' }}</span></summary><form class="form" method="post" action="{{ route('waiting-list-builder.fields.update',$field) }}">@csrf @method('PATCH')<div class="formgrid"><div class="field"><label>Pertanyaan</label><input name="label" value="{{ $field->label }}" required></div><div class="field"><label>Urutan</label><input type="number" name="position" value="{{ $field->position }}" min="0" max="999" required></div></div><div class="formgrid"><div class="field"><label>Placeholder</label><input name="placeholder" value="{{ $field->placeholder }}"></div><div class="field"><label>Bantuan</label><input name="help_text" value="{{ $field->help_text }}"></div></div>@unless($field->is_system)<div class="formgrid"><div class="field"><label>Tipe</label><select name="type">@foreach(['short_text'=>'Teks singkat','long_text'=>'Teks panjang','email'=>'Email','phone'=>'Nomor telepon','select'=>'Dropdown','month'=>'Bulan'] as $type=>$label)<option value="{{ $type }}" @selected($field->type===$type)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Pilihan dropdown</label><textarea name="options_text">{{ implode("\n",$field->options??[]) }}</textarea></div></div><label class="builder-check"><input type="checkbox" name="required" value="1" @checked($field->required)> Wajib diisi</label><label class="builder-check"><input type="checkbox" name="active" value="1" @checked($field->active)> Aktif</label>@endunless<button class="btn small">Simpan pertanyaan</button></form>@unless($field->is_system)<form class="waiting-disable-form" method="post" action="{{ route('waiting-list-builder.fields.destroy',$field) }}">@csrf @method('DELETE')<button class="btn danger small">Nonaktifkan</button></form>@endunless</details>@endforeach</div></details>
@endif
