<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('room_categories',function(Blueprint $t){$t->id();$t->string('name',80)->unique();$t->string('color',7)->default('#2C7668');$t->decimal('monthly_price',15,2);$t->timestamps();});
Schema::create('rooms',function(Blueprint $t){$t->id();$t->string('number',20)->unique();$t->foreignId('room_category_id')->constrained()->restrictOnDelete()->index();$t->unsignedTinyInteger('floor')->default(1);$t->enum('status',['KOSONG','TERISI','MAINTENANCE'])->default('KOSONG')->index();$t->timestamps();});
Schema::create('tenants',function(Blueprint $t){$t->id();$t->foreignId('room_id')->constrained()->restrictOnDelete()->index();$t->string('name',120);$t->string('phone',30);$t->string('identity_number',40)->nullable();$t->date('move_in');$t->date('move_out')->nullable();$t->date('next_due')->index();$t->boolean('active')->default(true)->index();$t->timestamps();$t->index(['active','next_due']);});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->constrained()->restrictOnDelete()->index();$t->decimal('amount',15,2);$t->date('paid_at')->index();$t->string('period',50);$t->enum('method',['Transfer','Cash','QRIS']);$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete()->index();$t->timestamps();});
Schema::create('expenses',function(Blueprint $t){$t->id();$t->string('title',150);$t->string('category',60)->index();$t->decimal('amount',15,2);$t->date('spent_at')->index();$t->text('notes')->nullable();$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete()->index();$t->timestamps();});
Schema::create('maintenances',function(Blueprint $t){$t->id();$t->foreignId('room_id')->constrained()->restrictOnDelete()->index();$t->string('title',150);$t->enum('status',['DIJADWALKAN','DIKERJAKAN','SELESAI'])->default('DIJADWALKAN')->index();$t->decimal('cost',15,2)->default(0);$t->date('reported_at')->index();$t->date('completed_at')->nullable();$t->text('notes')->nullable();$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete()->index();$t->foreignId('expense_id')->nullable()->unique()->constrained('expenses')->nullOnDelete();$t->timestamps();$t->index(['room_id','status']);});
if(DB::getDriverName()==='pgsql'){DB::statement('ALTER TABLE room_categories ADD CONSTRAINT room_categories_price_nonnegative CHECK (monthly_price >= 0)');DB::statement('ALTER TABLE payments ADD CONSTRAINT payments_amount_positive CHECK (amount > 0)');DB::statement('ALTER TABLE expenses ADD CONSTRAINT expenses_amount_positive CHECK (amount > 0)');DB::statement('ALTER TABLE maintenances ADD CONSTRAINT maintenances_cost_nonnegative CHECK (cost >= 0)');DB::statement('ALTER TABLE tenants ADD CONSTRAINT tenants_date_order CHECK (move_out IS NULL OR move_out >= move_in)');DB::statement('CREATE UNIQUE INDEX one_active_tenant_per_room ON tenants(room_id) WHERE active = true');}
if(DB::getDriverName()==='mysql'){DB::statement('ALTER TABLE tenants ADD active_room_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN active = 1 THEN room_id ELSE NULL END) STORED, ADD UNIQUE INDEX one_active_tenant_per_room (active_room_id)');}}
public function down():void{Schema::dropIfExists('maintenances');Schema::dropIfExists('expenses');Schema::dropIfExists('payments');Schema::dropIfExists('tenants');Schema::dropIfExists('rooms');Schema::dropIfExists('room_categories');}};
